/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Claim { 
    id?: number;
    content?: string;
    status?: Claim.StatusEnum;
    creation_Date?: number;
}
export namespace Claim {
    export type StatusEnum = 'IN_PROGRESS' | 'RESLOVED';
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Resloved: 'RESLOVED' as StatusEnum
    };
}


