/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    email?: string;
    password?: string;
    role?: RegisterRequest.RoleEnum;
    enable?: boolean;
}
export namespace RegisterRequest {
    export type RoleEnum = 'SUPER_ADMIN' | 'MINISTER_ADMIN';
    export const RoleEnum = {
        SuperAdmin: 'SUPER_ADMIN' as RoleEnum,
        MinisterAdmin: 'MINISTER_ADMIN' as RoleEnum
    };
}


